### PR TITLE
chore(deps): package-lock rebuild & GHA versions

### PR DESCRIPTION
**Pull request by dpogue**

### CODE REVIEW

**Review by erisu — COMMENTED** [review]
Code Changed LGTM but this PR will require a major release.

The current release has the following node engine requirement: 
```
"node": "^12.22.0 || ^14.17.0 || >=16.0.0"
```

The [`eslint-plugin-n`](https://github.com/eslint-community/eslint-plugin-n/blob/16.6.2/package.json#L5-L7) package which is bumped to the latest major major release contains the following engine requirement:
```
"node": ">=16.0.0"
```

**Comment by dpogue** [comment]
Ahh, I can downgrade that back to the previous version if we prefer (in which case this would just be bumping sub-dependencies).

**Comment by dpogue** [comment]
I downgraded so that we can merge the fix for the GHA warnings and resolve the npm security warnings, but it doesn't require a new version tagged.

**Review by erisu — APPROVED** [review]
LGTM

**Pull request merged**
